### ISSUE TITLE
CentOS 7.2 LE taste failure

### ISSUE THREAD

**Issue by eldebrim** [osuosl/packer-templates#25]
* [log file](https://github.com/osuosl/packer-templates/files/1167015/taster-20170721_172203-centos-le.txt)

 `openstack_taster "CentOS 7.2 LE"` fails some taster tests.

**Comment by DesertBeagle** [comment]
@eldebrim This isn't in our repo right now. Are you leaving this issue here to track the images that currently are not secure on the cluster?

**Comment by DesertBeagle** [comment]
CentOS 7.2 LE is no longer supported officially and in this repo. We are going to send a message out to the openpower mailing list letting them know about security vulnerabilities.
