### ISSUE TITLE
standardization of vm_name according to template name

### ISSUE THREAD

**Issue by knightsamar** [osuosl/packer-templates#31]
Some templates contain the `-openstack` suffix in their names but not in the `vm_name` attribute inside the `builder` hash. 

This is a bit annoying when parsing the template to determine where the built image would be found. Though the `vm_name` attribute seems not to be used anywhere else apart from the build and deploy processes, standardizing it with `-openstack` suffix would help in the longer term to distinguish from `-ganeti` vm perhaps. 

EDIT: explained the usage of `vm_name` a bit more.

**Comment by doublej472** [comment]
PR fixing this was merged, closing.
