### ISSUE TITLE
mitaka images don't build because of missing files

### ISSUE THREAD

**Issue by knightsamar** [osuosl/packer-templates#35]
They seem to require `chef/$image_name/cookbooks` which is not present and hence the build fails

**Comment by knightsamar** [comment]
The `openstack-test` cookbook is locatable now but not the others including `osl-openstack`

https://pastebin.osuosl.org/75681/

**Comment by knightsamar** [comment]
@ramereth ^

**Comment by ramereth** [comment]
@knightsamar the names of the folders underneath the chef folder should match the name of the json file (without .json of course).
