### ISSUE TITLE
build should not trigger/modify GitHub PR on non-push events

### ISSUE THREAD

**Issue by knightsamar** [osuosl/packer-templates#40]
It seems GitHub triggers builds on non-push events (probably because we use sync event?) on a PR which causes the verification builds data on the PR (the results and status of the build) to disappear.

**Comment by ramereth** [comment]
Currently we have ``Push`` and ``Pull Request`` events registered for the webhook. Should it be something different? Which job should not have been triggered?

**Comment by knightsamar** [comment]
https://jenkins.osuosl.org/job/packer_pipeline/327/console
https://jenkins.osuosl.org/job/packer_pipeline/326/console are examples of jobs which should not be triggered.

Right now I am filtering events in Jenkinsfile and handling only the `Pull Request` events but it has "sub-events" of which only the `synchronize` event seems useful to me.

**Comment by ramereth** [comment]
I fixed this by removing the push notification. The sync action in the PR notification does that too.
