### ISSUE TITLE
Blog/Student Story to post to OSL website

### ISSUE THREAD

**Issue by bielenpa** [osuosl/packer-templates#44]
@ramereth @doublej472 @JerryPeng0112 
JJ wrote a blog post/student story (don't know which area you want it to post) about Packer. Can you please get it into the OSL website? Thanks.

# Starting to use Packer to Build Images

### By JJ Frederick, Student Systems Engineer, OSL
At the OSL we use a [Packer](https://www.packer.io/) to build our images, because of the reproducible and easy work-flow it allows. We can create an entire operating system image based off a Linux distribution without any interaction! With this we are looking to add much more complete and automated testing.

To help with this we have decided to create a Github repository called [Packer Templates](https://github.com/osuosl/packer-templates). This is what the OSL will be using to generate OpenStack operating system images that many of our hosted projects use. We have been hard at work making this a reality for around 2 months and counting, and we still have work to do.

In order to get any Linux distribution to install automatically, you have to use their version of automatic installation. They all have different names and syntax, but generally all follow the same pattern:
1.	Boot the installation image and specify the web address holding the auto installation file through the bootloader
2.	Watch it install (and hopefully not fail)

Because we are using packer with QEMU (Virtual Machine software), even step 1 can be automated, meaning you just run the program and it does everything for you! One of the major reasons we made this into a Github repository is so we can take this a step further: automated testing. Each time we make a pull request with some changes to the installation scripts, we have Jenkins build the system images, then test them to make sure they work in some degree. This means we don't have to worry about some change in a script breaking an unrelated system, and we don't introduce bugs that break existing features!

**Comment by bielenpa** [comment]
I see the formatting changed when I pasted, so use your skills on that. Also, do your magic with the links that are included

**Comment by doublej472** [comment]
@bielenpa I've fixed the formatting to more closely match the email
